export const FETCHING_POSTS_REQUEST = 'FETCHING_POSTS_REQUEST';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAILED = 'FETCHING_POSTS_FAILED';

export const UPLOAD_POSTS_REQUEST = 'UPLOAD_POSTS_REQUEST';
export const UPLOAD_POSTS_SUCCESS = 'UPLOAD_POSTS_SUCCESS';
export const UPLOAD_POSTS_FAILED = 'UPLOAD_POSTS_FAILED';
export const RESET_POST_API_STORE = 'RESET_POST_API_STORE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_PROGRESS = 'UPLOAD_IMAGE_PROGRESS';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';
export const RESET_IMAGE_API_STORE = 'RESET_IMAGE_API_STORE';
